# Generated by Django 5.1.15 on 2026-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='ex. 0.1.0', max_length=32, verbose_name='Version')),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS'), ('source', 'Code source')], default='windows', max_length=16, verbose_name='Plateforme')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Titre (facultatif)')),
                ('notes', models.TextField(blank=True, default='', help_text='Nouveautés / corrections (une ligne par point).', verbose_name='Notes de version')),
                ('file', models.FileField(upload_to='releases/', verbose_name='Fichier (installeur)')),
                ('is_published', models.BooleanField(default=True, help_text='Décocher pour préparer une version sans la rendre visible.', verbose_name='Publiée')),
                ('downloads', models.PositiveIntegerField(default=0, editable=False, verbose_name='Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
            ],
            options={
                'verbose_name': "version de l'application",
                'verbose_name_plural': "versions de l'application",
                'ordering': ['-created_at'],
                'unique_together': {('version', 'platform')},
            },
        ),
    ]
