# Generated by Django 5.1.15 on 2026-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='downloads',
            field=models.PositiveIntegerField(default=0, help_text='Compteur automatique — modifiable manuellement si besoin.', verbose_name='Téléchargements'),
        ),
    ]
